#Headless service for clean dns record of each pod in statefulset.
#clusterIP: None - is not a fault, it's normal annotations
apiVersion: v1
kind: Service
metadata:
  name: {{ include "riak.fullname" . }}
  labels:
    {{- include "riak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 8098
      targetPort: 8098
      protocol: TCP
      name: http
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: protobuf
  selector:
    {{- include "riak.selectorLabels" . | nindent 4 }}
